spring.application.name=airbnb-clone
spring.data.mongodb.uri=${MONGO_URI:mongodb://127.0.0.1:27017/airbnb_clone}
server.port=5000
spring.jackson.property-naming-strategy=SNAKE_CASE
logging.level.root=WARN
logging.level.com.airbnbclone=INFO
