spring.application.name=airbnb-clone
spring.data.mongodb.uri=${MONGO_URI:mongodb://host.docker.internal:27017/airbnb_clone}
server.port=5000
spring.web.resources.static-locations=file:FrontEnd/dist/
spring.jackson.property-naming-strategy=SNAKE_CASE
logging.level.root=WARN
logging.level.com.airbnbclone=INFO
